name: Regenerate manifest

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'

jobs:
  regenerate:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Debug
        run: |
          git rev-parse HEAD
          ls -l
          sed -n '1,200p' create-manifest.py

      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files: data/**

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Remove old manifest
        run: rm -f manifest.json

      - name: Generate manifest
        env:
          # Variable de entorno con la lista de archivos modificados
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: python create-manifest.py

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add manifest.json

          if [ -n "$(git status --porcelain manifest.json)" ]; then
            git commit -m "Update manifest [skip ci]"
            git push
          else
            echo "No changes detected in manifest.json"
          fi
