name: Regenerate manifest

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'

jobs:
  regenerate:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Remove old manifest
        run: rm -f manifest.json

      - name: Generate manifest
        run: python create-manifest.py

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add manifest.json

          git diff --cached --quiet || git commit -m "Update manifest"

          git push
